### ISSUE TITLE
In paleo...

### ISSUE THREAD

**Issue by SamuelHill** [hmteditors/furman#1]
I noticed this for Team A so I wasn't sure who else is doing it but aren't we supposed to put [#] after repetitions of the same letter on a line in the paleography.csv?

> The second σ on line 26 would be urn:cts:greekLit:tlg0012.tlg001.msA:16.26@σ[2]

Next question, how do we capture a ligature? As of now my team (B), has put;

> urn:cts:greekLit:tlg0012.tlg001.msA:16.26@στ as the textURN
> "στ ligature" as the comment

Follow up to this, do we count a letter if it was in a ligature?

> στ in a word with urn:cts:greekLit:tlg0012.tlg001.msA:16.26@στ
> σ in a later word with urn:cts:greekLit:tlg0012.tlg001.msA:16.26@σ[2]

And lastly, do we note capitalizations and accentuations? What about terminal sigmas?

> urn:cts:greekLit:tlg0012.tlg001.msA:16.26@Ὀ
> urn:cts:greekLit:tlg0012.tlg001.msA:16.26@ὔ
> urn:cts:greekLit:tlg0012.tlg001.msA:16.26@ς

I'm not sure if these questions are answered somewhere so I figured I would ask on here. I think it might be helpful to put links to instructions for [each of the tasks on this page](http://www.homermultitext.org/hmt-docs/guides/how-to-edit/index.html).

**Comment by StephanieML** [comment]
1) Yes 2) That is correct 3) στ is distinct from ς  so count only in so far as they are the same string, so if you have two στ ligatures, you can do στ[2] but the sigma in the ligature would not count as a second sigma for single sigma strings 4) no to all of those

Thanks for your suggestions on these. I will keep a note of these questions for our updated editorial guide which we will (fingers crossed) be working on this spring.
