### ISSUE TITLE
Scholia XML

### ISSUE THREAD

**Issue by SamuelHill** [hmteditors/furman#10]
So we have guessed that we need to put the scholia text inside the lemma div in the XML files. And with that we have guess that for each scholion we will make a new div (B2 for example) with lemma, comment, and ref. We are unsure about which reference to put in ref (line of text it is talking about, or the scholion "urn:cts:greekLit.tlg5026....") and about what goes in the comment.

**Comment by JaneyCapers** [comment]
Also what should we do with the tei header portion?

**Comment by slyoung224** [comment]
We updated the formatting of the XML scholia.
