### ISSUE TITLE
End mark in interlinear scholia

### ISSUE THREAD

**Issue by JaneyCapers** [hmteditors/furman#13]
206v interlinear scholia ends with what appears to be a colon. We were unsure of this mark since that is not an end mark that we are familiar with. Is this simply to denote the ending of a scholia or is it an end mark of some sort, possibly a semi-colon (Greek question mark) that was written unclearly?

**Comment by JaneyCapers** [comment]
Solved by using lemma section.

**Comment by StephanieML** [comment]
If it looks like just a colon without the fish tail, we've treated it as a colon
