### ISSUE TITLE
Unknown Ligatures

### ISSUE THREAD

**Issue by JaneyCapers** [hmteditors/furman#15]
Dindorf on page 92 of volume two puts it down as περισπώμενον. The σπ ligature makes sense, but we couldn't see μενον from the end character. Instead that end character appears to be an αι tail on a μ.

urn:cite:hmt:vaimg.VA206VN-0708@0.44,0.1515,0.068,0.0152

**Comment by JaneyCapers** [comment]
For the time being, we used an unclear tag at the end of περισπώμ- to indicate our choice in endings.

**Comment by JaneyCapers** [comment]
περισπώμενον seems to be the only word that works here, so we're using that form.

**Comment by slyoung224** [comment]
urn:cite:hmt:vaimg.VA206VN-0708@0.4689,0.1532,0.0135,0.0109
