### ISSUE TITLE
Superimposed ο over τ but not Superscript

### ISSUE THREAD

**Issue by JaneyCapers** [hmteditors/furman#16]
It looks similar to a regular abreviation, but does not expand to a regular abreviation as far as we can see.

urn:cite:hmt:vaimg.VA206VN-0708@0.911,0.1645,0.014,0.0173

**Comment by JaneyCapers** [comment]
the το expands to the regular abbreviation τος  because it is attached to the rest of the word ἐνεστῶτος.

**Comment by StephanieML** [comment]
the superscript ο is a regular abbreviation for -ος
