### ISSUE TITLE
Temporary Fix to the Focus on Selection Tool

### ISSUE THREAD

**Issue by JaneyCapers** [hmteditors/furman#2]
Team B noticed that the “focus on selection” tool simply goes to an error page. The following is a temporary fix to the problem.

After selecting a portion of the text copy the URN.

Then replace the URN in the URL with the copied URN. 

> http://www.homermultitext.org/hmt-digital/ict.html?urn=urn:cite:hmt:vaimg.VA206VN-0708
> http://www.homermultitext.org/hmt-digital/ict.html?urn=  (paste here)
> http://www.homermultitext.org/hmt-digital/ict.html?urn=urn:cite:hmt:vaimg.VA206VN-0708@0.449,0.2104,0.326,0.0932

**Comment by StephanieML** [comment]
Thanks. This has been on the agenda to fix for awhile. Definitely make a copy of this work around and put it somewhere in the project wiki.
