### ISSUE TITLE
Faulty URN References

### ISSUE THREAD

**Issue by StephanieML** [hmteditors/furman#20]
B Team

You're scholia are looking great except for one tiny thing. The reference 'div' is for reference to the Iliadic line. Basically, saying this scholion is commenting on line # etc. So those urns will look like this:

urn:cts:greekLit:tlg0012.tlg001.msA:16.X

where X is the line number

Make sure you update those references before you do any further work on Book 16.

**Comment by StephanieML** [comment]
Sorry for the assigning confusion. It won't let me assign more than one person :(

**Comment by JaneyCapers** [comment]
Currently working on changing this in our scholia XMLs. Should we be more specific with URNs if a scholion does not have a lemma or if the lemma is shorter than the actual text being commented on? For example, an interlinear scholion above a single word that does not have a lemma might be specifically referencing a single word not the entire line. Alternatively, what about a scholion that talks about content on more than one line? In either of these cases would it be acceptable to use reference URNs such as

> urn:cts:greekLit:tlg0012.tlg001.msA:16.X@τοί[1]
> urn:cts:greekLit:tlg0012.tlg001.msA:16.X1-16.X2

respectively. Expanding on this should we be more specific about lines when we know the lemma? E.g., cite everything on a given line up to a "oti"...

_For now we are only using line numbers for the ref URN, but maybe this is something to think about for the future?_

**Comment by SamuelHill** [comment]
## Mix-up:

We use the range of lines format for some scholia. Example:

> urn:cts:greekLit:tlg5026.msAim:16.B2

This is referring to two asterisks, each on a distinct line.

**Comment by StephanieML** [comment]
So a couple different things here. 

1) Right now we've only used the specific word in a line references for interlinear scholia that are glossing specific words. For main scholia with lemmata we will not do this because the lemma, which you are recording serve that function. We will consider what to do for other scholia types, but right now the only scholia types that should have any reference to words in the line are interlinears.

2) For scholia talking about multiple lines you absolutely do give a range. So if it's talking about lines 1-2 of Book 16, your reference will be: urn:cts:greekLit:tlg0012.tlg001.msA:16.1-16.2. Make sure you are explicit with the book numbers. Otherwise, your reference is wrong.

**Comment by StephanieML** [comment]
Quick note, you should take the word reference out of the intermarginal scholion. 

for future reference, you only need numbers there if there's more than one instance of something, so even if we were referencing specific words in the line, you wouldn't have the number in the brackets.

**Comment by JaneyCapers** [comment]
We took the numbered bracket out of the word reference for the interlinear scholion.

**Comment by StephanieML** [comment]
awesome!
