### ISSUE TITLE
Unknown Character

### ISSUE THREAD

**Issue by JaneyCapers** [hmteditors/furman#21]
We cannot distinguish what this character is. Erpse (sp?) recorded it as ἃ

urn:cite:hmt:vaimg.VA206VN-0708@0.3987,0.2635,0.014,0.0129

**Comment by JaneyCapers** [comment]
We used Erpse's in the XML for now.

**Comment by StephanieML** [comment]
that's the abbreviation for kαὶ with a grave accent on it. You can see it's on it's way to looking similar to &
