### ISSUE TITLE
Abbreviation question

### ISSUE THREAD

**Issue by eliaseells** [hmteditors/furman#24]
urn:cite:hmt:vaimg.VA207RN-0378@0.39,0.169,0.019,0.015

Erbse has μῆκος, we only see μὴ. Is there a pronunciation of which we are not aware?

**Comment by StephanieML** [comment]
hm, well looking at everything around it, I read δια τὸ μὴ εὐ μήκως 

so perhaps we've got a little visual confusion there? Double check what's going on, but Erbse is known for adding things that aren't there.
