### ISSUE TITLE
 εἰς  with ending

### ISSUE THREAD

**Issue by JaneyCapers** [hmteditors/furman#25]
Is this εἰ an abreviation for εἰς?

> urn:cite:hmt:vaimg.VA206VN-0708@0.4085,0.3575,0.0118,0.0129

Does this σθαι get a macron over the ι or over the αι?

> urn:cite:hmt:vaimg.VA206VN-0708@0.4179,0.3582,0.0227,0.0097

Erbse has "εἰς <σ>θαι" with a macron over the "<σ>θαι"...
but we feel that the εἰ is a regular abreviation for εἰς and the σθαι is the ending that the scribe is talking about (this is why there is a macron). We found a similiar example in Ancient Greek Scholarship by Eleanor Dickey 4.1.29 Prepositions εἰς . 

_We have committed it as "εἰς σθαι" with a macron over "ι"_

**Comment by StephanieML** [comment]
I would record it as 
εἰς  θαι 

and mark θαι in 'rs' with the type@ 'waw'

no macrons. That horizontal line is indicating that it is not a parsable string and should be read as the syllable "θαι" 

likely Erbse has noted that it makes more sense to refer the string 'σθαι' but the scribe accidentally left out the second sigma.
