### ISSUE TITLE
Unsure of ending 

### ISSUE THREAD

**Issue by slyoung224** [hmteditors/furman#26]
Erbse has this as συλλαβῇ τὸ, is the mark above the beta an ῆι ending?

> urn:cite:hmt:vaimg.VA206VN-0708@0.3477,0.3896,0.045,0.0155

_for now we have it down as συλλαβῆι τὸ_

**Comment by StephanieML** [comment]
Erbse is wrong. That's the ην abbreviation, which you can put an accent on since it's abbreviated
