### ISSUE TITLE
Unsure of ending 

### ISSUE THREAD

**Issue by slyoung224** [hmteditors/furman#27]
Erbse has this as παρώξυνεν, is this a regular ending?

> urn:cite:hmt:vaimg.VA206VN-0708@0.3084,0.4335,0.0535,0.0152

_for now we have it down as παρώξυνεν_

**Comment by JaneyCapers** [comment]
We came across the same ending again in B6.

> urn:cite:hmt:vaimg.VA206VN-0708@0.258,0.5031,0.0288,0.0147

_for now we have it down as εἶπεν_

**Comment by StephanieML** [comment]
it is a regular abbreviation for εν
