### ISSUE TITLE
Unsure of abbreviation

### ISSUE THREAD

**Issue by JaneyCapers** [hmteditors/furman#29]
Dindorf has this recorded as χωρὶς. We only see χω-

> urn:cite:hmt:vaimg.VA206VN-0708@0.2933,0.527,0.0131,0.0129

_Currently recorded as χωρὶς_

**Comment by StephanieML** [comment]
very common, but it will need mark up.

χω will go in 'abbr' and χωρις  will go in 'expan' both sets of tags will be further wrapped in 'choice'
