### ISSUE TITLE
Unsure of mark

### ISSUE THREAD

**Issue by SamuelHill** [hmteditors/furman#3]
Between the second α on line 31 and the κ on line 32 there is a large 'upside down circumflex' looking thing that we are not sure of how to notate (or if it matters at all).

> urn:cite:hmt:vaimg.VA206VN-0708@0.517,0.3261,0.06,0.0406

**Comment by StephanieML** [comment]
Looks like a connecting slur for a compound word. You'll want to catalog these in a csv file. Here are some instructions on how to set up that file: https://github.com/HCMID/hmt-iliad10/wiki/How-to-Cite-Slurs

**Comment by SamuelHill** [comment]
The csv goes in the collections folder, correct?

**Comment by StephanieML** [comment]
Yup!
