### ISSUE TITLE
Unclear mark

### ISSUE THREAD

**Issue by JaneyCapers** [hmteditors/furman#30]
Should we in any way document this unclear mark above the alpha? It appears to be more than a smooth breathing, but the word ἀχιλλεά makes sense without any additions (this is how Dindorf recorded it). 

> urn:cite:hmt:vaimg.VA206VN-0708@0.3913,0.608,0.0481,0.0133

_We recorded it as “ἀχιλλεά"_

**Comment by StephanieML** [comment]
definitely mark it unclear. so you wrap the letter ἀ in 'unclear' then you wrap the whole word in 'w' so it doesn't get treated as two separate words
