### ISSUE TITLE
Unsure of word/ending

### ISSUE THREAD

**Issue by JaneyCapers** [hmteditors/furman#32]
Dindorf has recorded this as "στρατευομένῳ δὲ" We cannot figure out how the endings and abbreviations would work to become these words. 

> urn:cite:hmt:vaimg.VA206VN-0708@0.4059,0.6924,0.0568,0.0126

_For now we used Dindorf's recording without the iota subscript (στρατευομένωι δὲ) although we aren't confident that he is correct._

**Comment by StephanieML** [comment]
so the trailing bit off the mu indicates that it's 'μεν' and the raised squiggle is the ending for ῳ.

the δε is a common abbreviation for δε.

Subscripts are written adscript in this manuscript. You should make them subscript where appropriate. Check the rest of your work to make sure you don't have any iota subscripts recorded as adscript. It'll cause problems when we try to parse the Greek later
