### ISSUE TITLE
Unidentified symbol 

### ISSUE THREAD

**Issue by emmettvb** [hmteditors/furman#38]
urn:cite:hmt:vaimg.VA207VN-0709@0.5,0.3812,0.0667,0.0219

ὡς ἄν 

extra symbol above the sigma

**Comment by Eumaeus** [comment]
See [here](http://homermultitext.github.io/hmt-editors-guide/editorial-policies/).

Example: ἄ̆ν {urn:cts:greekLit:tlg0012.tlg001:9.101}
