### ISSUE TITLE
Unidentified symbol

### ISSUE THREAD

**Issue by SamuelHill** [hmteditors/furman#39]
urn:cite:hmt:vaimg.VA207VN-0709@0.7589,0.6665,0.1482,0.023

ἐκδύμεν ὄλεθρον

It seems to be that there is an elision after the ν in ἐκδύμεν... Any idea what the symbol is?

**Comment by Eumaeus** [comment]
Contrary to expectation, that seems to be an elision mark:

See [here](http://homermultitext.github.io/hmt-editors-guide/editorial-policies/)

elisions : Of the many possible Unicode characters for elision, use only Unicode straight single quote. If you use Sophokeys to enter Greek, note that this is not the character it generates automatically when entering Greek.

Example: ἄλλ' ἐν {urn:cts:greekLit:tlg0012.tlg001:9.235}
