### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by SamuelHill** [hmteditors/furman#5]
The notes on paleography link on [this page](http://www.homermultitext.org/resources.html) is broken...

**Comment by SamuelHill** [comment]
Also the HMT style guide doesn't show up (though I found it [here](http://shot.holycross.edu/chssummer2013/housestyle/HMTstyle-preview.pdf))

The link is also broken on [this page](http://www.homermultitext.org/hmt-docs/guides/)

**Comment by SamuelHill** [comment]
There is also a broken link [here](http://www.homermultitext.org/summer2014/editing/xmlediting.html)

**Comment by StephanieML** [comment]
Thanks, I've made issues in our hmt-web repo (https://github.com/homermultitext/hmt-web). Some of them we already knew about and have in line to fix with the next update to the web page. If you find any other broken links on the homermultitext web page, please make issues there.
