### ISSUE TITLE
Unsure of character/ligature

### ISSUE THREAD

**Issue by slyoung224** [hmteditors/furman#6]
In 206v line 29, unsure of whether επ ligature or ε and another character. URN in comment.

**Comment by JaneyCapers** [comment]
characters/ligature- urn:cite:hmt:vaimg.VA206VN-0708@0.8144,0.2942,0.0221,0.0105

word- urn:cite:hmt:vaimg.VA206VN-0708@0.8104,0.2857,0.0564,0.0258

**Comment by JaneyCapers** [comment]
Currently, it is marked in paleo as a επ ligature

**Comment by JaneyCapers** [comment]
Looks like it's the same as a ligature later on at urn:cite:hmt:vaimg.VA206VN-0708@0.7374,0.4438,0.024,0.0163 which is επ

**Comment by SamuelHill** [comment]
It is just an επ ligature, we were unsure when we were starting out
