### ISSUE TITLE
16.37 and 16.38 Abreviations

### ISSUE THREAD

**Issue by JaneyCapers** [hmteditors/furman#9]
The last words of both lines 37 and 38 have lines above them and missing characters. 
urn:cite:hmt:vaimg.VA206VN-0708@0.85,0.4207,0.094,0.0751
For XML editing how should we record these? Currently, we have them as abbreviations with expansions.

**Comment by brclar15** [comment]
The first one should be tagged up <choice><abbr>μηρ</abbr><expan>μήτηρ</expan></choice>
Biblical words, like μήτηρ, πατήρ, and οὐρανός are abbreviate in this way, with the first few letters and the last few letters to show what case it is, and then the bar on top.

the second one you can fully type out as όπασσον. that bar is just a ligature for a ν, not an abbreviation. sometimes that same bar stands for α, so be careful

happy editing!
